export const glyphs = [
  { id: 1, src: "./vfx/glyphs/glyph1.png", description: "Earth" },
  { id: 2, src: "./vfx/glyphs/glyph2.png", description: "Crater" },
  { id: 3, src: "./vfx/glyphs/glyph3.png", description: "Virgo" },
  { id: 4, src: "./vfx/glyphs/glyph4.png", description: "Bootes" },
  { id: 5, src: "./vfx/glyphs/glyph5.png", description: "Centaurus" },
  { id: 6, src: "./vfx/glyphs/glyph6.png", description: "Libra" },
  { id: 7, src: "./vfx/glyphs/glyph7.png", description: "Serpens Caput" },
  { id: 8, src: "./vfx/glyphs/glyph8.png", description: "Norma" },
  { id: 9, src: "./vfx/glyphs/glyph9.png", description: "Scorpio" },
  { id: 10, src: "./vfx/glyphs/glyph10.png", description: "Cra" },
  { id: 11, src: "./vfx/glyphs/glyph11.png", description: "Scutum" },
  { id: 12, src: "./vfx/glyphs/glyph12.png", description: "Sagitarius" },
  { id: 13, src: "./vfx/glyphs/glyph13.png", description: "Aquila" },
  { id: 14, src: "./vfx/glyphs/glyph14.png", description: "Mic" },
  { id: 15, src: "./vfx/glyphs/glyph15.png", description: "Capricorn" },
  { id: 16, src: "./vfx/glyphs/glyph16.png", description: "Pisces Austrinus" },
  { id: 17, src: "./vfx/glyphs/glyph17.png", description: "Equuleus" },
  { id: 18, src: "./vfx/glyphs/glyph18.png", description: "Aquarius" },
  { id: 19, src: "./vfx/glyphs/glyph19.png", description: "Pegasus" },
  { id: 20, src: "./vfx/glyphs/glyph20.png", description: "Sculptor" },
  { id: 21, src: "./vfx/glyphs/glyph21.png", description: "Pisces" },
  { id: 22, src: "./vfx/glyphs/glyph22.png", description: "Andromeda" },
  { id: 23, src: "./vfx/glyphs/glyph23.png", description: "Triangulum" },
  { id: 24, src: "./vfx/glyphs/glyph24.png", description: "Aries" },
  { id: 25, src: "./vfx/glyphs/glyph25.png", description: "Perseus" },
  { id: 26, src: "./vfx/glyphs/glyph26.png", description: "Cetus" },
  { id: 27, src: "./vfx/glyphs/glyph27.png", description: "Taurus" },
  { id: 28, src: "./vfx/glyphs/glyph28.png", description: "Auriga" },
  { id: 29, src: "./vfx/glyphs/glyph29.png", description: "Eridanus" },
  { id: 30, src: "./vfx/glyphs/glyph30.png", description: "Orion" },
  { id: 31, src: "./vfx/glyphs/glyph31.png", description: "Canis Minor" },
  { id: 32, src: "./vfx/glyphs/glyph32.png", description: "Monoceros" },
  { id: 33, src: "./vfx/glyphs/glyph33.png", description: "Gemini" },
  { id: 34, src: "./vfx/glyphs/glyph34.png", description: "Hydra" },
  { id: 35, src: "./vfx/glyphs/glyph35.png", description: "Lynx" },
  { id: 36, src: "./vfx/glyphs/glyph36.png", description: "Cancer" },
  { id: 37, src: "./vfx/glyphs/glyph37.png", description: "Sextans" },
  { id: 38, src: "./vfx/glyphs/glyph38.png", description: "Leo Minor" },
  { id: 39, src: "./vfx/glyphs/glyph39.png", description: "Leo" },
];

export default glyphs;